custom:
  bert_base_path: G:\download\Nu_tho_ngoc\tts-demo4\tts-demo\GPT_SoVITS\pretrained_models\chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: G:\download\Nu_tho_ngoc\tts-demo4\tts-demo\GPT_SoVITS\pretrained_models\chinese-hubert-base
  device: cpu
  flash_attn_enabled: true
  is_half: false
  t2s_weights_path: G:\download\Nu_tho_ngoc\tts-demo4\tts-demo\GPT_SoVITS\pretrained_models\GPT_weights\ellen_best_gpt.ckpt
  vits_weights_path: G:\download\Nu_tho_ngoc\tts-demo4\tts-demo\GPT_SoVITS\pretrained_models\SoVITS_weights\ellen_best_sovits.pth
default:
  bert_base_path: pretrained_models/chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: pretrained_models/chinese-hubert-base
  device: cpu
  flash_attn_enabled: true
  is_half: false
  t2s_weights_path: pretrained_models/s1bert25hz-2kh-longer-epoch=68e-step=50232.ckpt
  vits_weights_path: pretrained_models/s2G488k.pth
